### ISSUE TITLE
Scrip Failed when syncing account 

### ISSUE THREAD

**Issue by dna-24** [bstrdsmkr/1Channel#200]
I have the latest version installed on kodi and about 2 weeks ago i started getting script failed when trying to view my subscriptions or previously watched episodes.  I thought it was my acct but when i logged into primewires site everything was normal. Is this an issue with the add on or is this a connection issue with Primewire?

**Comment by tknorris** [comment]
You are probably using Android or Windows. There is a bug due to the version of python used on those platforms. Primewire has started requiring HTTPS for logging in and those platforms HTTPS won't work. If you check your log you'll see you are probably getting an error that says "internal error" for HTTPS. The problem will be fixed in the Kodi K*** when they upgrade the version of python used. Until then, nothing can be done.

**Comment by tknorris** [comment]
Note, if you are running Kodi on Linux, you can actually upgrade the version of Python being used on the system and it will fix the issue. I believe 2.7.10 is the first python version that doesn't have this issue.
